services:
  postgres:
    image: postgres:15-alpine
    container_name: B1test
    restart: always
    environment:
      POSTGRES_DB: B1DB
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: db_password
    ports:
      - "5434:5432"
